### ISSUE TITLE
Cannot open split GPX files in BaseCamp (ver. 4.2.3 mac).

### ISSUE THREAD

**Issue by ghost** [AntoCuc/GpxSplitter#3]
Hello.

First off i'd like to say I really like this program. However I thought I'd like to share with you an issue that I thought was important and needed to be resolved.

Basically after splitting a GPX into smaller ones (they all have 500 instructions or less so I would image they'd be compatible with my Garmin product) and loading them into BaseCamp I get greeted with the message:

"X is not a valid GPX file and could not be opened."

However, when I load them elsewhere such as Bikeroutetoaster they work perfectly.

I can't speak for my GPS device as I have not tested them on it. I have not been able to find a solution, maybe there is and I've not found it, still I feel it was something worth mentioning.

I want to start using this program in conjuction with BaseCamp/ my GPS. If this something that can be resolved in the next version then i'd be very happy!

All the best,

Ben.

**Comment by AntoCuc** [comment]
Hi Ben,
I just reactivated email notifications.
would you please send me sample of the GPX files you are trying to process and/or the output?
Regards,
Antonio

**Comment by AntoCuc** [comment]
Solved.
